### ISSUE TITLE
是否方便以补丁或代码树形式发布中文版本？

### ISSUE THREAD

**Issue by gaoyifan** [TelegramCN/webogram#1]
您好， 我是[telegram.ustclug.org](https://telegram.ustclug.org)的维护者。我们的一位用户在[评论](https://servers.blog.ustc.edu.cn/2016/10/add-telegram-web-service/)中提出，希望能够加入中文版翻译。

不知您是否方便以补丁的形式发布翻译？或直接在上游的代码树中修改？这样可能更方便追踪上游修改

盼回复~

**Comment by Hanxv** [comment]
https://github.com/TelegramCN/TelegramCN.github.io/blob/master/transifex/Web.json

https://telegramcn.github.io/cninst.html

**Comment by gaoyifan** [comment]
感谢回复😁
能否给[这个文件](https://github.com/TelegramCN/TelegramCN.github.io/blob/master/transifex/Web.json)增加授权协议呢？方便集成到构建脚本中

**Comment by Hanxv** [comment]
无协议，随意蹂躏。

**Comment by gaoyifan** [comment]
再次感谢！

**Comment by gaoyifan** [comment]
ping back: https://servers.ustclug.org/2016/10/web-telegram-use-chinese-as-default-lang/
